services:
  - type: web
    name: flir-discord-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python discord_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DISCORD_GUILD_ID
        value: "0"
      - key: BOT_PREFIX
        value: "!"
      - key: DEBUG_MODE
        value: "False"
